### PR TITLE
[WIP] Use iterable directly

### LINKED ISSUE #1: Don't convert input to an array
https://github.com/sindresorhus/p-settle/blob/5533d855599609609b68ab267e00eed7d30b8d50/index.js#L3

The iterable should be used directly instead of converting to an array. It would have the benefit of better supporting generated sequences.

A pull request would be wonderful 🙌🌟
## 

Related: https://github.com/sindresorhus/p-map/issues/1

### PR DESCRIPTION
**Pull request by sotojuan**
Fixes #1.

I'm assuming there's a bit more to this but at least this is a good start.

### CODE REVIEW

**Comment by sindresorhus** [comment]
You don't know the iterable length up-front. That's what complicates it. With the current logic the length is used twice.

**Comment by sotojuan** [comment]
Iterables have to define a `next` function that returns a `done` boolean right? We could loop through it until we hit `done === false`. If it's just an array, we can use `length`.

**Comment by sindresorhus** [comment]
> Iterables have to define a next function that returns a done boolean right? We could loop through it until we hit done === false

Yup.

> If it's just an array, we can use length.

Nope. Arrays are iterables too. No custom logic needed.

**Comment by sindresorhus** [comment]
Closing as this went stale and doesn't have any actual changes ;)

**Pull request closed without merging**
